
spring:
   profiles: prd
   datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.249.79:3306/farm?useUnicode=true&amp;characterEncoding=UTF-8
    username: farm
    password: farm2018
weixin:
  appid: wxef310c6d87af833e
  appsecret: appsecret